Create table all_sequences (
	sequence_name varchar2(100),
	sequence_owner varchar2(100)
);

Insert into all_sequences (sequence_name, sequence_owner) values ('SEC_SEQ_IDUTENTE', 'GILDACE');
Insert into all_sequences (sequence_name, sequence_owner) values ('SEQ_IDPROFILO', 'GILDACE');

commit;

Create table all_tables (OWNER                     VARCHAR2(30) NOT NULL,
                         TABLE_NAME                VARCHAR2(30) NOT NULL,
                         TABLESPACE_NAME           VARCHAR2(30),
                         INITIAL_EXTENT            NUMBER,
                         TEMPORARY                 VARCHAR2(1),
                         NESTED                    VARCHAR2(3),
                         DURATION                  VARCHAR2(15)
);

Insert into all_tables (OWNER, TABLE_NAME, TABLESPACE_NAME, INITIAL_EXTENT, TEMPORARY, NESTED, DURATION) Values ('GILDACE', 'SEC_DEC_RUOLI', 'USERS', 65536, 'N', 'NO', null);
Insert into all_tables (OWNER, TABLE_NAME, TABLESPACE_NAME, INITIAL_EXTENT, TEMPORARY, NESTED, DURATION) Values ('GILDACE', 'SEC_FUNZIONIRUOLI', 'USERS', 65536, 'N', 'NO', null);
Insert into all_tables (OWNER, TABLE_NAME, TABLESPACE_NAME, INITIAL_EXTENT, TEMPORARY, NESTED, DURATION) Values ('GILDACE', 'SEC_PROFILI', 'USERS', 65536, 'N', 'NO', null);
Insert into all_tables (OWNER, TABLE_NAME, TABLESPACE_NAME, INITIAL_EXTENT, TEMPORARY, NESTED, DURATION) Values ('GILDACE', 'SEC_DEC_MENUUTENTE', 'USERS', 65536, 'N', 'NO', null);
Insert into all_tables (OWNER, TABLE_NAME, TABLESPACE_NAME, INITIAL_EXTENT, TEMPORARY, NESTED, DURATION) Values ('GILDACE', 'SEC_MENUUTENTERUOLI', 'USERS', 65536, 'N', 'NO', null);
Insert into all_tables (OWNER, TABLE_NAME, TABLESPACE_NAME, INITIAL_EXTENT, TEMPORARY, NESTED, DURATION) Values ('GILDACE', 'SEC_MENURUOLI', 'USERS', 65536, 'N', 'NO', null);
Insert into all_tables (OWNER, TABLE_NAME, TABLESPACE_NAME, INITIAL_EXTENT, TEMPORARY, NESTED, DURATION) Values ('GILDACE', 'SEC_DEC_TIPIVOCE', 'USERS', 65536, 'N', 'NO', null);
Insert into all_tables (OWNER, TABLE_NAME, TABLESPACE_NAME, INITIAL_EXTENT, TEMPORARY, NESTED, DURATION) Values ('GILDACE', 'SEC_DEC_MENU', 'USERS', 65536, 'N', 'NO', null);
Insert into all_tables (OWNER, TABLE_NAME, TABLESPACE_NAME, INITIAL_EXTENT, TEMPORARY, NESTED, DURATION) Values ('GILDACE', 'SEC_DEC_FUNZIONI', 'USERS', 65536, 'N', 'NO', null);
Insert into all_tables (OWNER, TABLE_NAME, TABLESPACE_NAME, INITIAL_EXTENT, TEMPORARY, NESTED, DURATION) Values ('GILDACE', 'AFORISMI', 'USERS', 65536, 'N', 'NO', null);
Insert into all_tables (OWNER, TABLE_NAME, TABLESPACE_NAME, INITIAL_EXTENT, TEMPORARY, NESTED, DURATION) Values ('GILDACE', 'SEC_UTENTI', 'USERS', 65536, 'N', 'NO', null);
commit;

Create table all_tab_columns (OWNER                VARCHAR2(30) NOT NULL,
                              TABLE_NAME           VARCHAR2(30) NOT NULL,
                              COLUMN_NAME          VARCHAR2(30) NOT NULL,
                              DATA_TYPE            VARCHAR2(106),
                              DATA_TYPE_MOD        VARCHAR2(3),
                              DATA_TYPE_OWNER      VARCHAR2(120),
                              DATA_LENGTH          NUMBER NOT NULL,
                              DATA_PRECISION       NUMBER,
                              DATA_SCALE           NUMBER,
                              NULLABLE             VARCHAR2(1),
                              COLUMN_ID            NUMBER,
                              DEFAULT_LENGTH       NUMBER,
                              DATA_DEFAULT         LONG
);

Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_UTENTI', 'FOTO', 'BLOB', null, null, 4000, null, null, 'Y', 9, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_UTENTI', 'LOCALE', 'VARCHAR2', null, null, 5, null, null, 'Y', 8, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_UTENTI', 'EMAILPASSWORD', 'VARCHAR2', null, null, 100, null, null, 'Y', 7, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_UTENTI', 'EMAIL', 'VARCHAR2', null, null, 100, null, null, 'Y', 6, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_UTENTI', 'PASSWORD', 'VARCHAR2', null, null, 10, null, null, 'Y', 5, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_UTENTI', 'USERID', 'VARCHAR2', null, null, 10, null, null, 'Y', 4, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_UTENTI', 'COGNOME', 'VARCHAR2', null, null, 100, null, null, 'Y', 3, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_UTENTI', 'NOME', 'VARCHAR2', null, null, 100, null, null, 'Y', 2, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_UTENTI', 'IDUTENTE', 'NUMBER', null, null, 22, 38, 0, 'N', 1, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_PROFILI', 'DATAFINE', 'DATE', null, null, 7, null, null, 'Y', 5, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_PROFILI', 'DATAINIZIO', 'DATE', null, null, 7, null, null, 'N', 4, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_PROFILI', 'CODRUOLO', 'VARCHAR2', null, null, 10, null, null, 'Y', 3, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_PROFILI', 'IDUTENTE', 'NUMBER', null, null, 22, 38, 0, 'Y', 2, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_PROFILI', 'IDPROFILO', 'NUMBER', null, null, 22, 38, 0, 'N', 1, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_MENUUTENTERUOLI', 'FLAGACCESSO', 'VARCHAR2', null, null, 1, null, null, 'Y', 3, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_MENUUTENTERUOLI', 'CODRUOLO', 'VARCHAR2', null, null, 10, null, null, 'N', 2, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_MENUUTENTERUOLI', 'CODMENUUTENTE', 'VARCHAR2', null, null, 100, null, null, 'N', 1, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_MENURUOLI', 'FLAGACCESSO', 'VARCHAR2', null, null, 1, null, null, 'Y', 3, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_MENURUOLI', 'CODRUOLO', 'VARCHAR2', null, null, 10, null, null, 'N', 2, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_MENURUOLI', 'CODMENU', 'VARCHAR2', null, null, 100, null, null, 'N', 1, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_FUNZIONIRUOLI', 'FLAGACCESSO', 'VARCHAR2', null, null, 1, null, null, 'Y', 3, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_FUNZIONIRUOLI', 'CODRUOLO', 'VARCHAR2', null, null, 10, null, null, 'N', 2, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_FUNZIONIRUOLI', 'CODFUNZIONE', 'VARCHAR2', null, null, 100, null, null, 'N', 1, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_TIPIVOCE', 'FLAGMENUUTENTE', 'VARCHAR2', null, null, 1, null, null, 'Y', 6, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_TIPIVOCE', 'FLAGVALIDO', 'VARCHAR2', null, null, 1, null, null, 'N', 5, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_TIPIVOCE', 'POSIZIONE', 'NUMBER', null, null, 22, 38, 0, 'N', 4, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_TIPIVOCE', 'DESCRIZIONELUNGA', 'VARCHAR2', null, null, 100, null, null, 'N', 3, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_TIPIVOCE', 'DESCRIZIONEBREVE', 'VARCHAR2', null, null, 20, null, null, 'N', 2, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_TIPIVOCE', 'CODTIPOVOCE', 'VARCHAR2', null, null, 10, null, null, 'N', 1, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_RUOLI', 'FLAGVALIDO', 'VARCHAR2', null, null, 1, null, null, 'N', 5, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_RUOLI', 'POSIZIONE', 'NUMBER', null, null, 22, 38, 0, 'N', 4, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_RUOLI', 'DESCRIZIONELUNGA', 'VARCHAR2', null, null, 100, null, null, 'N', 3, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_RUOLI', 'DESCRIZIONEBREVE', 'VARCHAR2', null, null, 20, null, null, 'N', 2, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_RUOLI', 'CODRUOLO', 'VARCHAR2', null, null, 10, null, null, 'N', 1, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENUUTENTE', 'LINK', 'VARCHAR2', null, null, 200, null, null, 'Y', 8, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENUUTENTE', 'IMGHTML', 'VARCHAR2', null, null, 100, null, null, 'Y', 7, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENUUTENTE', 'CODTIPOVOCE', 'VARCHAR2', null, null, 10, null, null, 'N', 6, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENUUTENTE', 'FLAGVALIDO', 'VARCHAR2', null, null, 1, null, null, 'N', 5, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENUUTENTE', 'POSIZIONE', 'NUMBER', null, null, 22, 38, 0, 'N', 4, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENUUTENTE', 'DESCRIZIONELUNGA', 'VARCHAR2', null, null, 100, null, null, 'N', 3, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENUUTENTE', 'DESCRIZIONEBREVE', 'VARCHAR2', null, null, 20, null, null, 'N', 2, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENUUTENTE', 'CODMENUUTENTE', 'VARCHAR2', null, null, 100, null, null, 'N', 1, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENU', 'LINK', 'VARCHAR2', null, null, 200, null, null, 'Y', 9, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENU', 'IMGHTML', 'VARCHAR2', null, null, 100, null, null, 'Y', 8, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENU', 'LIVELLO', 'NUMBER', null, null, 22, null, 0, 'N', 7, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENU', 'CODTIPOVOCE', 'VARCHAR2', null, null, 10, null, null, 'N', 6, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENU', 'FLAGVALIDO', 'VARCHAR2', null, null, 1, null, null, 'N', 5, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENU', 'POSIZIONE', 'NUMBER', null, null, 22, 38, 0, 'N', 4, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENU', 'DESCRIZIONELUNGA', 'VARCHAR2', null, null, 100, null, null, 'N', 3, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENU', 'DESCRIZIONEBREVE', 'VARCHAR2', null, null, 20, null, null, 'N', 2, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_MENU', 'CODMENU', 'VARCHAR2', null, null, 100, null, null, 'N', 1, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_FUNZIONI', 'FLAGVALIDO', 'VARCHAR2', null, null, 1, null, null, 'N', 5, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_FUNZIONI', 'POSIZIONE', 'NUMBER', null, null, 22, 38, 0, 'N', 4, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_FUNZIONI', 'DESCRIZIONELUNGA', 'VARCHAR2', null, null, 100, null, null, 'N', 3, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_FUNZIONI', 'DESCRIZIONEBREVE', 'VARCHAR2', null, null, 20, null, null, 'N', 2, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'SEC_DEC_FUNZIONI', 'CODFUNZIONE', 'VARCHAR2', null, null, 100, null, null, 'N', 1, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'AFORISMI', 'DATAULTIMAPUBLICAZIONE', 'DATE', null, null, 7, null, null, 'Y', 4, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'AFORISMI', 'AUTORE', 'VARCHAR2', null, null, 100, null, null, 'Y', 3, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'AFORISMI', 'AFORISMA', 'VARCHAR2', null, null, 1000, null, null, 'Y', 2, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'AFORISMI', 'IDAFORISMA', 'NUMBER', null, null, 22, 38, 0, 'N', 1, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'VIEW_SEC_UTENTI', 'EMAIL', 'VARCHAR2', null, null, 100, null, null, 'Y', 6, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'VIEW_SEC_UTENTI', 'PASSWORD', 'VARCHAR2', null, null, 10, null, null, 'Y', 5, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'VIEW_SEC_UTENTI', 'FOTO', 'BLOB', null, null, 4000, null, null, 'Y', 9, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'VIEW_SEC_UTENTI', 'NOME', 'VARCHAR2', null, null, 100, null, null, 'Y', 2, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'VIEW_SEC_UTENTI', 'EMAILPASSWORD', 'VARCHAR2', null, null, 100, null, null, 'Y', 7, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'VIEW_SEC_UTENTI', 'LOCALE', 'VARCHAR2', null, null, 5, null, null, 'Y', 8, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'VIEW_SEC_UTENTI', 'COGNOME', 'VARCHAR2', null, null, 100, null, null, 'Y', 3, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'VIEW_SEC_UTENTI', 'USERID', 'VARCHAR2', null, null, 10, null, null, 'Y', 4, null, null);
Insert into all_tab_columns (OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_TYPE_MOD, DATA_TYPE_OWNER, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, DEFAULT_LENGTH, DATA_DEFAULT) Values ('GILDACE', 'VIEW_SEC_UTENTI', 'IDUTENTE', 'NUMBER', null, null, 22, 38, 0, 'N', 1, null, null);
commit;

Create table all_col_comments (OWNER       VARCHAR2(30) NOT NULL,
                               TABLE_NAME  VARCHAR2(30) NOT NULL,
                               COLUMN_NAME VARCHAR2(30) NOT NULL,
                               COMMENTS    VARCHAR2(4000)
);

Create table all_tab_comments  (OWNER      VARCHAR2(30) NOT NULL,
                                TABLE_NAME VARCHAR2(30) NOT NULL ,
                                TABLE_TYPE VARCHAR2(11),
                                COMMENTS   VARCHAR2(4000)
);

Create table ALL_mviews (OWNER                  VARCHAR2(30) NOT NULL,
                         MVIEW_NAME             VARCHAR2(30) NOT NULL
);

